name: 'Build Pine Icons'
description: 'Build Pine Icon library'

inputs:
  node-version:
    description: 'The version of node to use'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check out latest
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache Node modules
      uses: actions/cache@v3
      id: icons-node-modules
      env:
        cache-name: icons-node-modules
      with:
        path: ./libs/icons/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}-v1

    - name: Set SHA
      uses: nrwl/nx-set-shas@v3

    - name: Install Dependencies
      if: steps.cache-node-modules.ouputs.cache-hit != true || steps.changed-files.outputs.any_changed == 'true'
      run: lerna bootstrap -- --frozen-lockfile --immutable
      shell: bash

    - name: Build Icons
      run: yarn nx run icons:build
      shell: bash

    - name: Upload Icons Build Archive
      uses: ./.github/workflows/actions/upload-archive
      with:
        name: icons-build
        output: IconsBuild.zip
        paths: libs/icons/dist libs/icons/components lib/icons/icons lib/icons/www

    - name: Upload Icons Source
      uses: ./.github/workflows/actions/upload-archive
      with:
        name: icons-src
        output: IconsSrc.zip
        paths: libs/icons/src
