# TODO: Change these to `pine` instead of `sage` once the repo has been changed
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: sage
  description: The Sage Design System
  tags:
    - design
    - ux
spec:
  owner: design-system-services
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sage
  description: The Sage Design System Library
  tags:
    - design
    - ux
    - javascript
    - typescript
    - web-components
  annotations:
    backstage.io/source-location: url:https://github.com/Kajabi/sage/tree/next
    github.com/project-slug: Kajabi/sage
spec:
  type: library
  lifecycle: production
  owner: design-system-services
  system: sage
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: sage.mono-repo
spec:
  targets:
    - ./libs/core/catalog-info.yaml
    - ./libs/icons/catalog-info.yaml
    - ./libs/react/catalog-info.yaml
