name: 'Test Lint'
descriptions: 'Runs lint for affected projects'

inputs:
  node-version:
    description: 'The version of node to use'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check out latest
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache node_modules
      uses: actions/cache@v3
      id: cache-node-modules
      env:
        cache-name: cache-node-modules
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: Install Dependencies
      if: steps.cache-node-modules.ouputs.cache-hit != true
      run: npm ci
      shell: bash

    - name: Lint
      run : npx nx affected --target=lint --parallel=3
      shell: bash
