name: 'Test Lint'
descriptions: 'Runs lint for affected projects'

inputs:
  node-version:
    description: 'The version of node to use'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check out latest
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install Dependencies
      run: yarn install --frozen-lockfile --immutable
      shell: bash

    - name: Lint
      run : yarn nx affected --target=lint --parallel=3
      shell: bash
