/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DocSource {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLDocSourceElement extends Components.DocSource, HTMLStencilElement {
    }
    var HTMLDocSourceElement: {
        prototype: HTMLDocSourceElement;
        new (): HTMLDocSourceElement;
    };
    interface HTMLElementTagNameMap {
        "doc-source": HTMLDocSourceElement;
    }
}
declare namespace LocalJSX {
    interface DocSource {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "doc-source": DocSource;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "doc-source": LocalJSX.DocSource & JSXBase.HTMLAttributes<HTMLDocSourceElement>;
        }
    }
}
