name: 'Build Pine Core'
description: 'Builds Pine Core library'

inputs:
  node-version:
    description: 'The version of node to use'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check out latest
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache Node modules
      uses: actions/cache@v3
      id: core-node-modules
      env:
        cache-name: core-node-modules
      with:
        path: ./libs/core/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}-v1

    - name: Set SHA
      uses: nrwl/nx-set-shas@v3

    - name: Install Dependencies
      run: npm ci
      working-directory: './libs/core'
      shell: bash

    - name: Build Core
      run: npx nx run core:build  --ci
      shell: bash

    - name: Upload artifacts
      uses: ./.github/workflows/actions/upload-archive
      with:
        name: core-build
        output: libs/core/CoreBuild.zip
        paths: libs/core/css libs/core/dist libs/core/loader libs/core/src/components.d.ts
