/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SageIcon {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLSageIconElement extends Components.SageIcon, HTMLStencilElement {
    }
    var HTMLSageIconElement: {
        prototype: HTMLSageIconElement;
        new (): HTMLSageIconElement;
    };
    interface HTMLElementTagNameMap {
        "sage-icon": HTMLSageIconElement;
    }
}
declare namespace LocalJSX {
    interface SageIcon {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "sage-icon": SageIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sage-icon": LocalJSX.SageIcon & JSXBase.HTMLAttributes<HTMLSageIconElement>;
        }
    }
}
