/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PdsIcon {
        /**
          * The color of the icon
         */
        "color"?: string;
        /**
          * This a combination of both `name` and `src`. If a `src` url is detected it will set the `src` property. Otherwise it assumes it's a built-in named SVG and set the `name` property.
         */
        "icon"?: any;
        /**
          * The name of the icon to use from the built-in set.
         */
        "name"?: string;
        /**
          * The size of the icon. This can be 'small', 'regular', 'medium', large, or a custom value (40px, 1rem, etc)
         */
        "size"?: | 'small'   // 12px
    | 'regular'  // 16px
    | 'medium'  // 20px
    | 'large'   // 24px
    | 'auto'
    | string;
    }
}
declare global {
    interface HTMLPdsIconElement extends Components.PdsIcon, HTMLStencilElement {
    }
    var HTMLPdsIconElement: {
        prototype: HTMLPdsIconElement;
        new (): HTMLPdsIconElement;
    };
    interface HTMLElementTagNameMap {
        "pds-icon": HTMLPdsIconElement;
    }
}
declare namespace LocalJSX {
    interface PdsIcon {
        /**
          * The color of the icon
         */
        "color"?: string;
        /**
          * This a combination of both `name` and `src`. If a `src` url is detected it will set the `src` property. Otherwise it assumes it's a built-in named SVG and set the `name` property.
         */
        "icon"?: any;
        /**
          * The name of the icon to use from the built-in set.
         */
        "name"?: string;
        /**
          * The size of the icon. This can be 'small', 'regular', 'medium', large, or a custom value (40px, 1rem, etc)
         */
        "size"?: | 'small'   // 12px
    | 'regular'  // 16px
    | 'medium'  // 20px
    | 'large'   // 24px
    | 'auto'
    | string;
    }
    interface IntrinsicElements {
        "pds-icon": PdsIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pds-icon": LocalJSX.PdsIcon & JSXBase.HTMLAttributes<HTMLPdsIconElement>;
        }
    }
}
