/* eslint-disable */
/* tslint:disable */
/* auto-generated react proxies */
import { createReactComponent } from './react-component-lib';

import type { JSX } from '@pine-ds/core/components';

import { defineCustomElement as defineMockPdsModal } from '@pine-ds/core/components/mock-pds-modal.js';
import { defineCustomElement as definePdsAccordion } from '@pine-ds/core/components/pds-accordion.js';
import { defineCustomElement as definePdsAlert } from '@pine-ds/core/components/pds-alert.js';
import { defineCustomElement as definePdsAvatar } from '@pine-ds/core/components/pds-avatar.js';
import { defineCustomElement as definePdsBox } from '@pine-ds/core/components/pds-box.js';
import { defineCustomElement as definePdsButton } from '@pine-ds/core/components/pds-button.js';
import { defineCustomElement as definePdsCheckbox } from '@pine-ds/core/components/pds-checkbox.js';
import { defineCustomElement as definePdsChip } from '@pine-ds/core/components/pds-chip.js';
import { defineCustomElement as definePdsCopytext } from '@pine-ds/core/components/pds-copytext.js';
import { defineCustomElement as definePdsDivider } from '@pine-ds/core/components/pds-divider.js';
import { defineCustomElement as definePdsDropdown } from '@pine-ds/core/components/pds-dropdown.js';
import { defineCustomElement as definePdsDropdownItem } from '@pine-ds/core/components/pds-dropdown-item.js';
import { defineCustomElement as definePdsImage } from '@pine-ds/core/components/pds-image.js';
import { defineCustomElement as definePdsInput } from '@pine-ds/core/components/pds-input.js';
import { defineCustomElement as definePdsLink } from '@pine-ds/core/components/pds-link.js';
import { defineCustomElement as definePdsLoader } from '@pine-ds/core/components/pds-loader.js';
import { defineCustomElement as definePdsModal } from '@pine-ds/core/components/pds-modal.js';
import { defineCustomElement as definePdsModalContent } from '@pine-ds/core/components/pds-modal-content.js';
import { defineCustomElement as definePdsModalFooter } from '@pine-ds/core/components/pds-modal-footer.js';
import { defineCustomElement as definePdsModalHeader } from '@pine-ds/core/components/pds-modal-header.js';
import { defineCustomElement as definePdsPopover } from '@pine-ds/core/components/pds-popover.js';
import { defineCustomElement as definePdsProgress } from '@pine-ds/core/components/pds-progress.js';
import { defineCustomElement as definePdsRadio } from '@pine-ds/core/components/pds-radio.js';
import { defineCustomElement as definePdsRow } from '@pine-ds/core/components/pds-row.js';
import { defineCustomElement as definePdsSelect } from '@pine-ds/core/components/pds-select.js';
import { defineCustomElement as definePdsSortable } from '@pine-ds/core/components/pds-sortable.js';
import { defineCustomElement as definePdsSortableItem } from '@pine-ds/core/components/pds-sortable-item.js';
import { defineCustomElement as definePdsSwitch } from '@pine-ds/core/components/pds-switch.js';
import { defineCustomElement as definePdsTab } from '@pine-ds/core/components/pds-tab.js';
import { defineCustomElement as definePdsTable } from '@pine-ds/core/components/pds-table.js';
import { defineCustomElement as definePdsTableBody } from '@pine-ds/core/components/pds-table-body.js';
import { defineCustomElement as definePdsTableCell } from '@pine-ds/core/components/pds-table-cell.js';
import { defineCustomElement as definePdsTableHead } from '@pine-ds/core/components/pds-table-head.js';
import { defineCustomElement as definePdsTableHeadCell } from '@pine-ds/core/components/pds-table-head-cell.js';
import { defineCustomElement as definePdsTableRow } from '@pine-ds/core/components/pds-table-row.js';
import { defineCustomElement as definePdsTabpanel } from '@pine-ds/core/components/pds-tabpanel.js';
import { defineCustomElement as definePdsTabs } from '@pine-ds/core/components/pds-tabs.js';
import { defineCustomElement as definePdsText } from '@pine-ds/core/components/pds-text.js';
import { defineCustomElement as definePdsTextarea } from '@pine-ds/core/components/pds-textarea.js';
import { defineCustomElement as definePdsTooltip } from '@pine-ds/core/components/pds-tooltip.js';

export const MockPdsModal = /*@__PURE__*/createReactComponent<JSX.MockPdsModal, HTMLMockPdsModalElement>('mock-pds-modal', undefined, undefined, defineMockPdsModal);
export const PdsAccordion = /*@__PURE__*/createReactComponent<JSX.PdsAccordion, HTMLPdsAccordionElement>('pds-accordion', undefined, undefined, definePdsAccordion);
export const PdsAlert = /*@__PURE__*/createReactComponent<JSX.PdsAlert, HTMLPdsAlertElement>('pds-alert', undefined, undefined, definePdsAlert);
export const PdsAvatar = /*@__PURE__*/createReactComponent<JSX.PdsAvatar, HTMLPdsAvatarElement>('pds-avatar', undefined, undefined, definePdsAvatar);
export const PdsBox = /*@__PURE__*/createReactComponent<JSX.PdsBox, HTMLPdsBoxElement>('pds-box', undefined, undefined, definePdsBox);
export const PdsButton = /*@__PURE__*/createReactComponent<JSX.PdsButton, HTMLPdsButtonElement>('pds-button', undefined, undefined, definePdsButton);
export const PdsCheckbox = /*@__PURE__*/createReactComponent<JSX.PdsCheckbox, HTMLPdsCheckboxElement>('pds-checkbox', undefined, undefined, definePdsCheckbox);
export const PdsChip = /*@__PURE__*/createReactComponent<JSX.PdsChip, HTMLPdsChipElement>('pds-chip', undefined, undefined, definePdsChip);
export const PdsCopytext = /*@__PURE__*/createReactComponent<JSX.PdsCopytext, HTMLPdsCopytextElement>('pds-copytext', undefined, undefined, definePdsCopytext);
export const PdsDivider = /*@__PURE__*/createReactComponent<JSX.PdsDivider, HTMLPdsDividerElement>('pds-divider', undefined, undefined, definePdsDivider);
export const PdsDropdown = /*@__PURE__*/createReactComponent<JSX.PdsDropdown, HTMLPdsDropdownElement>('pds-dropdown', undefined, undefined, definePdsDropdown);
export const PdsDropdownItem = /*@__PURE__*/createReactComponent<JSX.PdsDropdownItem, HTMLPdsDropdownItemElement>('pds-dropdown-item', undefined, undefined, definePdsDropdownItem);
export const PdsImage = /*@__PURE__*/createReactComponent<JSX.PdsImage, HTMLPdsImageElement>('pds-image', undefined, undefined, definePdsImage);
export const PdsInput = /*@__PURE__*/createReactComponent<JSX.PdsInput, HTMLPdsInputElement>('pds-input', undefined, undefined, definePdsInput);
export const PdsLink = /*@__PURE__*/createReactComponent<JSX.PdsLink, HTMLPdsLinkElement>('pds-link', undefined, undefined, definePdsLink);
export const PdsLoader = /*@__PURE__*/createReactComponent<JSX.PdsLoader, HTMLPdsLoaderElement>('pds-loader', undefined, undefined, definePdsLoader);
export const PdsModal = /*@__PURE__*/createReactComponent<JSX.PdsModal, HTMLPdsModalElement>('pds-modal', undefined, undefined, definePdsModal);
export const PdsModalContent = /*@__PURE__*/createReactComponent<JSX.PdsModalContent, HTMLPdsModalContentElement>('pds-modal-content', undefined, undefined, definePdsModalContent);
export const PdsModalFooter = /*@__PURE__*/createReactComponent<JSX.PdsModalFooter, HTMLPdsModalFooterElement>('pds-modal-footer', undefined, undefined, definePdsModalFooter);
export const PdsModalHeader = /*@__PURE__*/createReactComponent<JSX.PdsModalHeader, HTMLPdsModalHeaderElement>('pds-modal-header', undefined, undefined, definePdsModalHeader);
export const PdsPopover = /*@__PURE__*/createReactComponent<JSX.PdsPopover, HTMLPdsPopoverElement>('pds-popover', undefined, undefined, definePdsPopover);
export const PdsProgress = /*@__PURE__*/createReactComponent<JSX.PdsProgress, HTMLPdsProgressElement>('pds-progress', undefined, undefined, definePdsProgress);
export const PdsRadio = /*@__PURE__*/createReactComponent<JSX.PdsRadio, HTMLPdsRadioElement>('pds-radio', undefined, undefined, definePdsRadio);
export const PdsRow = /*@__PURE__*/createReactComponent<JSX.PdsRow, HTMLPdsRowElement>('pds-row', undefined, undefined, definePdsRow);
export const PdsSelect = /*@__PURE__*/createReactComponent<JSX.PdsSelect, HTMLPdsSelectElement>('pds-select', undefined, undefined, definePdsSelect);
export const PdsSortable = /*@__PURE__*/createReactComponent<JSX.PdsSortable, HTMLPdsSortableElement>('pds-sortable', undefined, undefined, definePdsSortable);
export const PdsSortableItem = /*@__PURE__*/createReactComponent<JSX.PdsSortableItem, HTMLPdsSortableItemElement>('pds-sortable-item', undefined, undefined, definePdsSortableItem);
export const PdsSwitch = /*@__PURE__*/createReactComponent<JSX.PdsSwitch, HTMLPdsSwitchElement>('pds-switch', undefined, undefined, definePdsSwitch);
export const PdsTab = /*@__PURE__*/createReactComponent<JSX.PdsTab, HTMLPdsTabElement>('pds-tab', undefined, undefined, definePdsTab);
export const PdsTable = /*@__PURE__*/createReactComponent<JSX.PdsTable, HTMLPdsTableElement>('pds-table', undefined, undefined, definePdsTable);
export const PdsTableBody = /*@__PURE__*/createReactComponent<JSX.PdsTableBody, HTMLPdsTableBodyElement>('pds-table-body', undefined, undefined, definePdsTableBody);
export const PdsTableCell = /*@__PURE__*/createReactComponent<JSX.PdsTableCell, HTMLPdsTableCellElement>('pds-table-cell', undefined, undefined, definePdsTableCell);
export const PdsTableHead = /*@__PURE__*/createReactComponent<JSX.PdsTableHead, HTMLPdsTableHeadElement>('pds-table-head', undefined, undefined, definePdsTableHead);
export const PdsTableHeadCell = /*@__PURE__*/createReactComponent<JSX.PdsTableHeadCell, HTMLPdsTableHeadCellElement>('pds-table-head-cell', undefined, undefined, definePdsTableHeadCell);
export const PdsTableRow = /*@__PURE__*/createReactComponent<JSX.PdsTableRow, HTMLPdsTableRowElement>('pds-table-row', undefined, undefined, definePdsTableRow);
export const PdsTabpanel = /*@__PURE__*/createReactComponent<JSX.PdsTabpanel, HTMLPdsTabpanelElement>('pds-tabpanel', undefined, undefined, definePdsTabpanel);
export const PdsTabs = /*@__PURE__*/createReactComponent<JSX.PdsTabs, HTMLPdsTabsElement>('pds-tabs', undefined, undefined, definePdsTabs);
export const PdsText = /*@__PURE__*/createReactComponent<JSX.PdsText, HTMLPdsTextElement>('pds-text', undefined, undefined, definePdsText);
export const PdsTextarea = /*@__PURE__*/createReactComponent<JSX.PdsTextarea, HTMLPdsTextareaElement>('pds-textarea', undefined, undefined, definePdsTextarea);
export const PdsTooltip = /*@__PURE__*/createReactComponent<JSX.PdsTooltip, HTMLPdsTooltipElement>('pds-tooltip', undefined, undefined, definePdsTooltip);
