name: 'Sage Framework Build'

on:
  push:
    branches: [main, next]
  pull_request:
    branches: [ "**" ]

# When pushing a new commit we should cancel
# the previous run
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-icons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ./.github/workflows/actions/build-icons

  build-core:
    needs: [build-icons]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/build-core

  test-lint:
    needs: [build-core]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/test-lint

  test-specs:
    needs: [build-core]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/test-spec
