name: 'Mercury Rising Release'

on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: The branch name, tag, or SHA to be checked out. This can also be left blank.
        default: ''

  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: The branch name, tag, or SHA to be checked out. This can also be left blank.
        default: ''

jobs:
    release:
      permissions:
        id-token: write
      uses: ./.github/workflows/release-packages.yml
      with:
        preid: 'mercury'
        tag: 'next'
        version: 'preminor'
      secrets: inherit

    finalize-release:
      needs: release
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
            ref: ${{ inputs.ref }}

        - name: Configure user
          run: |
            git config user.name "DSS Automation Bot"
            git config user.email "dev+github-bot@kajabi.com"

        - name: Create GitHub Release
          run: lerna version preminor --yes --force-publish='*' --conventional-commits --create-release github --preid=mercury
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          shell: bash

