name: 'Mercury Rising Release'

on:
  push:
    branches: [mercury-rising]

  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: The branch name, tag, or SHA to be checked out. This can also be left blank.
        default: ''

jobs:
    release:
      permissions:
        id-token: write
      uses: ./.github/workflows/schedule-release.yml
      with:
        preid: 'mercury'
        tag: 'next'
        version: 'premajor'
      secrets: inherit
