name: "Pine Nightly Automations"

on:
  schedule:
    - cron: '00 11 * * 1-5' # 11 am UTC Mon-Fri
  workflow_dispatch:
    inputs:
      preid:
        type: choice
        description: Which prerelease id should be used? This is only needed when a version is "prepatch", "preminor", "premajor", or "prerelease".
        options:
          - ''
          - alpha
          - beta
          - rc
          - next

      tag:
        type: choice
        required: true
        description: Which npm tag should this be published to
        options:
          - latest
          - next
          - dev

      version:
        type: choice
        required: true
        description: Which version should be published?
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
          - prerelease

jobs:
  export-icons:
    uses: ./.github/workflows/icon-export.yml
    with:
      preid: ${{ inputs.preid || '' }}
      tag: ${{ inputs.tag || 'nightly' }}
      version: ${{ inputs.version || '' }}
    secrets: inherit
