name: 'Release Packages'

on:
  workflow_call:
    inputs:
      preid:
        description: 'The prerelease id used when doing a prerelease. e.g prerelease, premajor, preminor, etc.'
        type: string
        default: ''

      ref:
        description: 'This could be a branch name, tag, or a SHA.'
        type: string
        default: ''

      tag:
        description: 'The tag to publish on NPM.'
        required: true
        type: string

      version:
        description: 'The type of version to release.'
        required: true
        type: string

    secrets:
      NPM_TOKEN:
        required: true

jobs:
  release-core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}

      - name: Configure user
        run: |
          git config user.name "DSS Automation Bot"
          git config user.email "dev+github-bot@kajabi.com"

      - name: Publish Core
        uses: ./.github/workflows/actions/publish-npm
        with:
          preid: ${{ inputs.preid }}
          project: 'core'
          tag: ${{ inputs.tag }}
          token: ${{ secrets.NPM_TOKEN }}
          version: ${{ inputs.version }}
          working-directory: 'libs/core'

      - name: Cache Built core
        uses: ./.github/workflows/actions/upload-archive
        with:
          name: pine-core
          output: libs/core/CoreBuild.zip
          paths: libs/core/dist libs/core/components libs/core/css libs/core/hydrate libs/core/loader libs/core/src/components.d.ts

  release-react:
    needs: [release-core]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}

      - name: Restore core built cache
        uses: ./.github/workflows/actions/download-archive
        with:
          name: pine-core
          path: ./libs/core
          filename: CoreBuild.zip

      - name: Configure user
        run: |
          git config user.name "Kajabi Automation Bot"
          git config user.email "dev+github-bot@kajabi.com"

      - name: Publish React
        uses: ./.github/workflows/actions/publish-npm
        with:
          preid: ${{ inputs.preid }}
          project: 'react'
          tag: ${{ inputs.tag }}
          token: ${{ secrets.NPM_TOKEN }}
          version: ${{ inputs.version }}
          working-directory: 'libs/react'

      - name: Cache Built react
        uses: ./.github/workflows/actions/upload-archive
        with:
          name: pine-react
          output: libs/react/ReactBuild.zip
          paths: libs/react/dist libs/react/css
